# -*- coding: utf-8 -*-
"""pr0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CTz3u2X9B6yq0GwN4q_WxQAz9mbUGO4q
"""

#imported important libraries
import pandas as pd
import numpy as np
from sklearn.externals import joblib

#reading the dataset
x = pd.read_csv('f.csv')

#seperated the independent and dependent values to repective variables 
#x = df.drop(['prognosis'],axis =1)
#y = df['prognosis']
pkl_filename = 'dt1.pkl'
#saved the model 
# Load the model from the file 
dt1 = joblib.load('dt1.pkl')

#choices should be key value of symptoms space separated eg: "1 12 26 130"
def diag(w):
	a = list(range(2,134))
	b = w.split(',')
	for i in range(0, len(b)): 
		b[i] = int(b[i])
	count = 0
	while count < len(b):
		item_to_replace =  b[count]
		replacement_value = 1
		indices_to_replace = [i for i,x in enumerate(a) if x==item_to_replace]
		count = count+1
		for i in indices_to_replace:
			a[i] = replacement_value
	a = [0 if x !=1 else x for x in a]
	y_diagnosis = dt1.predict([a])
	y_pred_2 = dt1.predict_proba([a])
	return(y_diagnosis[0])

#diag("11,22,33")

