# -*- coding: utf-8 -*-
"""predictor.ipynb

Automatically generated by Colaboratory.

"""

#imported important libraries
import pandas as pd
import numpy as np
import joblib 

#reading the dataset
x = pd.read_csv('f.csv')

#seperated the independent and dependent values to repective variables 
#x = df.drop(['prognosis'],axis =1)
#y = df['prognosis']
pkl_filename = 'dt(1).pkl'
#saved the model 
# Load the model from the file 
dt = joblib.load('my_model_for_healthcare.pkl')

#choices should be key value of symptoms space separated eg: "1 12 26 130"
def diag(b):
  a = list(range(2,134))
  #i_name  = (input('Enter your name :'))
  #i_age = (int(input('Enter your age:')))
  #for i in range(len(x.columns)):
   # print(str(i+1+1) + ":", x.columns[i])
  #choices = input('Enter the Serial no.s which is your Symptoms are exist:  ')
  #b = [int(x) for x in choices.split()]
  count = 0
  while count < len(b):
    item_to_replace =  b[count]
    replacement_value = 1
    indices_to_replace = [i for i,x in enumerate(a) if x==item_to_replace]
    count += 1
    for i in indices_to_replace:
      a[i] = replacement_value
  a = [0 if x !=1 else x for x in a]
  y_diagnosis = dt.predict([a])
  y_pred_2 = dt.predict_proba([a])
  #print(('Name of the infection = %s , confidence score of : = %s') %(y_diagnosis[0],y_pred_2.max()* 100),'%' )
  return(y_diagnosis[0])
  #print(('Name = %s , Age : = %s') %(i_name,i_age))

#diag("1 ")

